### ISSUE TITLE
voice.rate doesn't work

### ISSUE THREAD

**Issue by jason79** [DeepHorizons/tts#3]
voice.rate(3)

Traceback (most recent call last):
  File "C:\Users\jason\Google Drive\python\test3.py       ", line 9, in <module>
    voice.rate(3)
AttributeError: 'Sapi' object has no attribute 'rate'

**Comment by DeepHorizons** [comment]
The readme was wrong. It used to be `rate`, but changed to `set_rate` at some point. I updated the readme to reflect that.
